<?php
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
/** @noinspection PhpIncludeInspection */
//To Solve File REST_Controller not found
require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

/**
 * This is an example of a few basic user interaction methods you could use
 * all done with a hardcoded array
 *
 * @package         CodeIgniter
 * @subpackage      Rest Server
 * @category        Controller
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver
 */
class Rest_server extends REST_Controller {

    function __construct()
    {

        parent::__construct();

        /*$this->methods['users_get']['limit'] = 500; // 500 requests per hour per user/key*/
        $this->methods['users_post']['limit'] = 100; // 100 requests per hour per user/key
        /*$this->methods['users_delete']['limit'] = 50; // 50 requests per hour per user/key*/
        $this->load->model('user_model');
    }
    public function users_post()
    {
        $cek_user = $this->user_model->cek_username();
        if($cek_user > 0){
            $message = [
                'error' => 'username sudah ada'
            ];
        } else {
            $this->user_model->insert();
            $message = [
                'id' => 100, // Automatically generated by the model
                'username' => $this->post('username'),
                'email' => $this->post('email'),
                'message' => 'Added a resource'
            ];    
        }
        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
}
